# This config uses industrial_ci (https://github.com/ros-industrial/industrial_ci.git).
# For troubleshooting, see README (https://github.com/ros-industrial/industrial_ci/blob/master/README.rst)

name: Industrial CI

on:
  push:
    branches: [main, devel]
  pull_request:
    branches: [main, devel]
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  industrial_ci:
    name: ROS Tests
    runs-on: ubuntu-18.04
    strategy:
      matrix: # matrix is the product of entries
        ROS_DISTRO: [melodic]
        ROS_REPO: [main]
    env:
      ADDITIONAL_DEBS: python-catkin-lint
      PARALLEL_BUILDS: 8
      PARALLEL_TESTS: 1
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: "ros-industrial/industrial_ci@master" # run industrial_ci
        env:
          ROS_DISTRO: ${{ matrix.ROS_DISTRO }}
          ROS_REPO: ${{ matrix.ROS_REPO }}
